{ pkgs }: (pkgs.emacsPackagesFor pkgs.emacs-unstable).emacsWithPackages (
  epkgs: with epkgs; [
    ace-window
    catppuccin-theme
    company
    consult
    consult-flycheck
    dirvish
    doom-modeline
    embark
    embark-consult
    envrc
    evil
    evil-collection
    flycheck
    general
    ligature
    lsp-mode
    lsp-ui
    magit
    marginalia
    nerd-icons
    nerd-icons-completion
    nerd-icons-dired
    nerd-icons-ibuffer
    nix-mode
    ob-mermaid
    orderless
    org-bullets
    org-roam
    pdf-tools
    tree-sitter
    tree-sitter-langs
    treesit-grammars.with-all-grammars
    vertico
    vterm
    which-key
  ]
)
