{ pkgs }: (pkgs.emacsPackagesFor pkgs.emacs-unstable).emacsWithPackages (
  epkgs: with epkgs; [
    ace-window
    catppuccin-theme
    company
    consult
    doom-modeline
    embark
    embark-consult
    envrc
    evil
    evil-collection
    ligature
    lsp-mode
    lsp-ui
    magit
    marginalia
    nerd-icons
    nerd-icons-dired
    nerd-icons-ibuffer
    nerd-icons-completion
    nix-mode
    orderless
    org-bullets
    org-roam
    tree-sitter
    tree-sitter-langs
    treesit-grammars.with-all-grammars
    vertico
    vterm
  ]
)
