;; Tangle the config file only when it has changed
(let* ((default-directory user-emacs-directory)
       (org-file "config.org")
       (el-file "config.el")
       (early-org-file "early.org")
       (early-el-file "early.el")
       (changed-at (file-attribute-modification-time (file-attributes org-file)))
       (early-changed-at (file-attribute-modification-time (file-attributes org-file))))
  (require 'org-macs)
  (unless (org-file-newer-than-p el-file changed-at)
    (require 'ob-tangle)
    (org-babel-tangle-file org-file el-file "emacs-lisp"))
  (unless (org-file-newer-than-p early-el-file early-changed-at)
    (require 'ob-tangle)
    (org-babel-tangle-file early-org-file early-el-file "emacs-lisp"))
  (load-file early-el-file))
